--------------캠핑렌트 DB--------------
--[회원 테이블]--

--MEMBER 테이블, 시퀀스 유무 확인 구문
DROP TABLE MEMBER;
DROP SEQUENCE MEMBER_SEQ;

--MEMBER 테이블 시퀀스 생성
CREATE TABLE MEMBER(
    MEMNO NUMBER NOT NULL,
    MEMNICK VARCHAR2(100) NOT NULL UNIQUE,
    MEMID VARCHAR2(100) NOT NULL UNIQUE,
    MEMPW VARCHAR2(100) NOT NULL,
    MEMNAME VARCHAR2(100) NOT NULL,
    MEMZIP VARCHAR2(100) NOT NULL,
    MEMADDR VARCHAR2(1000) NOT NULL,
    MEMADDR2 VARCHAR2(100) NULL,
    MEMPHONE VARCHAR2(100) NOT NULL,
    MEMBIRTH DATE NOT NULL,
    MEMGENDER NUMBER NOT NULL CHECK(MEMGENDER IN(1, 2)), 
    MEMCHK VARCHAR2(1) DEFAULT('N') NOT NULL CHECK(MEMCHK IN('Y','N')),
    MEMCODE NUMBER DEFAULT(2) NOT NULL CHECK(MEMCODE IN(1, 2)),
    MEMFILE VARCHAR2(2000) NULL,
    CONSTRAINT MEMNO_PK PRIMARY KEY(MEMNO)
);

CREATE SEQUENCE MEMBER_SEQ;

--데이터 삽입
INSERT INTO MEMBER
VALUES(MEMBER_SEQ.NEXTVAL, 'CarMing관리자', 'admin@naver.com', 'admin', '관리자', '13444', '서울특별시 강남구 역삼동', '역삼아이파크 102동 206호', '010-1234-1234', SYSDATE, 1, 'Y', 1, '관리자.PNG');

--테이블 전체 조회
SELECT * FROM MEMBER; 

--[렌트 상태 테이블]--

--RENTSTATE 테이블, 시퀀스 유무 확인
DROP TABLE RENTSTATE cascade constraint;
DROP SEQUENCE RENTSTATE_SEQ;

--RENTSTATE 테이블 시퀀스 생성
CREATE TABLE RENTSTATE(
    STATENO NUMBER NOT NULL,
    STATENAME VARCHAR2(100) NOT NULL,
    CONSTRAINT STATENO_PK PRIMARY KEY(STATENO)
);

CREATE SEQUENCE RENTSTATE_SEQ;

--데이터 삽입
INSERT INTO RENTSTATE
VALUES(RENTSTATE_SEQ.NEXTVAL, '장바구니');
INSERT INTO RENTSTATE
VALUES(RENTSTATE_SEQ.NEXTVAL, '결제 완료');
INSERT INTO RENTSTATE
VALUES(RENTSTATE_SEQ.NEXTVAL, '대여중');
INSERT INTO RENTSTATE
VALUES(RENTSTATE_SEQ.NEXTVAL, '반납 신청');
INSERT INTO RENTSTATE
VALUES(RENTSTATE_SEQ.NEXTVAL, '반납 완료');
INSERT INTO RENTSTATE
VALUES(RENTSTATE_SEQ.NEXTVAL, '반납일 초과'); 

--테이블 전체 조회
SELECT * FROM RENTSTATE;

--[캠핑렌트 카테고리 테이블]--

--PCATEGORY 테이블, 시퀀스 유무 확인 구문
DROP TABLE PCATEGORY cascade constraint;
DROP SEQUENCE PCATEGORY_SEQ;

--PCATEGORY 테이블, 시퀀스 생성
CREATE TABLE PCATEGORY(
    PCATEGORYNO NUMBER NOT NULL,
    PCATEGORYNAME VARCHAR2(100) NOT NULL,
    CONSTRAINT PCATEGORYNO_PK PRIMARY KEY(PCATEGORYNO)
);

CREATE SEQUENCE PCATEGORY_SEQ;

--데이터 삽입
INSERT INTO PCATEGORY
VALUES(PCATEGORY_SEQ.NEXTVAL, '텐트 / 타프');
INSERT INTO PCATEGORY
VALUES(PCATEGORY_SEQ.NEXTVAL, '매트 / 침낭');
INSERT INTO PCATEGORY
VALUES(PCATEGORY_SEQ.NEXTVAL, '코펠 / 버너 / 취사');
INSERT INTO PCATEGORY
VALUES(PCATEGORY_SEQ.NEXTVAL, '체어 / 테이블');
INSERT INTO PCATEGORY
VALUES(PCATEGORY_SEQ.NEXTVAL, '화로대 / BBQ');

--COMMENT(주석) 설정--
COMMENT ON COLUMN PCATEGORY.PCATEGORYNO IS '상품카테고리 번호';
COMMENT ON COLUMN PCATEGORY.PCATEGORYNAME IS '상품카테고리 이름';

--테이블 전체 조회
SELECT * FROM PCATEGORY;

--데이터 삭제
DELETE FROM PCATEGORY
WHERE PCATEGORYNO = 3;

--[캠핑렌트  상품 테이블]--

--PRODUCT 테이블, 시퀀스 유무 확인 구문
DROP TABLE PRODUCT cascade constraint;
DROP SEQUENCE PRODUCT_SEQ;

--PRODUCT 테이블, 시퀀스 생성
CREATE TABLE PRODUCT(
    PNO NUMBER NOT NULL,
    PCATEGORYNO NUMBER NOT NULL,
    PNAME VARCHAR2(100) NOT NULL,
    PPRICE NUMBER NOT NULL,
    PDESC VARCHAR2(1000) NOT NULL,
    PFILE VARCHAR2(1000) NOT NULL,
    PAMOUNT NUMBER NOT NULL,
    PPATH VARCHAR2(1000) NULL,
    CONSTRAINT PNO_PK PRIMARY KEY(PNO),
    CONSTRAINT CATEGORYNO_FK FOREIGN KEY(PCATEGORYNO) REFERENCES PCATEGORY(PCATEGORYNO) ON DELETE CASCADE
);

CREATE SEQUENCE PRODUCT_SEQ;
--데이터 삽입
INSERT INTO PRODUCT
VALUES(PRODUCT_SEQ.NEXTVAL, 3, '겨울 나기 텐트', 15000, '이것은 이미지입니다', '파일입니다.', 50, "spring");
--데이터 삭제
DELETE 
FROM PRODUCT
WHERE PCATEGORYNO=1;
--컬럼 추가(파일 경로)
ALTER TABLE PRODUCT ADD PPATH VARCHAR2(1000) NULL;
ALTER TABLE PRODUCT ADD PFILE2 VARCHAR2(1000) NULL;
ALTER TABLE PRODUCT ADD PFILE3 VARCHAR2(1000) NULL;
--테이블 전체 조회
SELECT * FROM PRODUCT;

--[캠핑렌트 리뷰]--

--REVIEW 테이블 시퀀스 유무 확인
DROP TABLE REVIEW cascade constraint;
DROP SEQUENCE REVIEW_SEQ;

--REVIEW 테이블 시퀀스 생성
CREATE TABLE REVIEW(
    REVIEWNO NUMBER NOT NULL,
    PNO NUMBER NOT NULL,
    REVIEWCONTEXT LONG NOT NULL,
    REVIEWDATE DATE NOT NULL,
    REVIEWWRITER VARCHAR2(200) NOT NULL,
    REVIEWSTAR NUMBER NOT NULL,
    CONSTRAINT REVIEWNO_PK PRIMARY KEY(REVIEWNO),
    CONSTRAINT REVIEW_PNO_FK FOREIGN KEY(PNO) REFERENCES PRODUCT(PNO) ON DELETE CASCADE
);

CREATE SEQUENCE REVIEW_SEQ;

--데이터 삽입
INSERT INTO REVIEW
VALUES(REVIEW_SEQ.NEXTVAL, 60, '나쁜거 같아요.', SYSDATE, 'monaa22', 3);

--데이터 삭제
DELETE 
FROM REVIEW;
--테이블 전체
SELECT * FROM REVIEW;

--해당 게시글 리뷰 갯수만 가져오는 SQL--
SELECT COUNT(*)
FROM REVIEW
WHERE PNO = 62;
--[캠핑렌트 장바구니]--

--CART 테이블 시퀀스 유무 확인
DROP TABLE CART cascade constraint;
DROP SEQUENCE CART_SEQ;

--CART 테이블 시퀀스 생성
CREATE TABLE CART(
    CARTNO NUMBER NOT NULL,
    CAMOUNT NUMBER NOT NULL,
    STARTDATE DATE NULL,
    ENDDATE DATE NULL,
    MEMNO NUMBER NOT NULL,
    PNO NUMBER NOT NULL,
    STATENO NUMBER DEFAULT(1) NOT NULL,
    CONSTRAINT CARTNO_PK PRIMARY KEY(CARTNO),
    CONSTRAINT CART_PNO_FK FOREIGN KEY(PNO) REFERENCES PRODUCT(PNO) ON DELETE CASCADE,
    CONSTRAINT STATENO_FK FOREIGN KEY(STATENO) REFERENCES RENTSTATE(STATENO) ON DELETE CASCADE    
);



CREATE TABLE CART(
    CARTNO NUMBER NOT NULL,
    CAMOUNT NUMBER NOT NULL,
    STARTDATE DATE NULL,
    ENDDATE DATE NULL,
    MEMNO NUMBER NOT NULL,
    PNO NUMBER NOT NULL,
    STATENO NUMBER NOT NULL,
    PCATEGORYNO NUMBER NOT NULL,
    CONSTRAINT CARTNO_PK PRIMARY KEY(CARTNO),
    CONSTRAINT PCATEGORYNO_FK FOREIGN KEY (PCATEGORYNO) REFERENCES PCATEGORY (PCATEGORYNO) ON DELETE CASCADE,
    CONSTRAINT CART_PNO_FK FOREIGN KEY(PNO) REFERENCES PRODUCT(PNO) ON DELETE CASCADE,
    CONSTRAINT STATENO_FK FOREIGN KEY(STATENO) REFERENCES RENTSTATE(STATENO) ON DELETE CASCADE    
);


CREATE SEQUENCE CART_SEQ;

--데이터 삽입

--테이블 전체 조회
SELECT * FROM CART; 

--테이블 변경
ALTER TABLE CART ADD PCATEGORYNO NUMBER NULL;
ALTER TABLE CART ADD CONSTRAINT PCATEGORYNO_FK FOREIGN KEY (PCATEGORYNO) REFERENCES PCATEGORY (PCATEGORYNO) ON DELETE CASCADE;

--[캠핑렌트 결제 테이블]--

--PAY 테이블 시퀀스 유무 확인
DROP TABLE PAY cascade constraint;
DROP SEQUENCE PAY_SEQ;

--PAY 테이블 시퀀스 생성
CREATE TABLE PAY(
    PAYNO NUMBER NOT NULL,
    CARTNO NUMBER NOT NULL,
    METHOD VARCHAR2(100) NOT NULL,
    ADDR VARCHAR2(1000) NOT NULL,
    TOTALPRICE NUMBER NOT NULL,
    PAYDAY DATE NOT NULL,
    CONSTRAINT PAYNO_PK PRIMARY KEY(PAYNO),
    CONSTRAINT PAY_CARTNO_FK FOREIGN KEY(CARTNO) REFERENCES CART(CARTNO) ON DELETE CASCADE
);

CREATE SEQUENCE PAY_SEQ;

--데이터 삽입
INSERT INTO PAY
VALUES(PAY_SEQ.NEXTVAL, 75, 'CARD', '서울시 강남구 역삼동', 500000, SYSDATE);
INSERT INTO PAY
VALUES(PAY_SEQ.CURRVAL, 76, 'CARD', '서울시 강남구 역삼동', 500000, SYSDATE);
INSERT INTO PAY
VALUES(PAY_SEQ.NEXTVAL, 77, 'CARD', '서울시 강남구 역삼동', 500000, SYSDATE);
INSERT INTO PAY
VALUES(PAY_SEQ.CURRVAL, 78, 'CARD', '서울시 강남구 역삼동', 500000, SYSDATE);
--테이블 전체 조회
SELECT * FROM PAY;
SELECT PAY_SEQ.NEXTVAL FROM DUAL;
SELECT PAY_SEQ.CURRVAL FROM DUAL;
--테이블 제약조건 변경
ALTER TABLE PAY DROP PRIMARY KEY;
ALTER TABLE PAY ADD CONSTRAINT PAYNO_CARTNO_PK PRIMARY KEY(PAYNO, CARTNO);

		SELECT
		C.*,
		M.MEMNICK,
		RS.STATENAME,
		P.PNAME,
		PC.PCATEGORYNAME,
		PY.PAYNO,
		PY.TOTALPRICE
		FROM CART C
		JOIN MEMBER M
		ON C.MEMNO = M.MEMNO
		JOIN RENTSTATE RS
		ON C.STATENO = RS.STATENO
		JOIN PRODUCT P
		ON C.PNO = P.PNO
		JOIN PCATEGORY PC
		ON C.PCATEGORYNO = PC.PCATEGORYNO
		JOIN PAY PY
		ON C.CARTNO = PY.CARTNO




--테스트(PRODUCT, CART, PAY) 테이블 조인
SELECT COUNT(PNAME)-1
FROM 
CART C INNER JOIN 
PAY P ON (C.CARTNO = P.CARTNO) LEFT OUTER JOIN
PRODUCT PR ON (C.PNO = PR.PNO)
WHERE PAYNO = 49;

--테스트(PAY, CART)테이블 조인
SELECT *
FROM CART C
JOIN PAY P ON(C.CARTNO = P.CARTNO);

UPDATE 
(	
	SELECT C.STATENO
	FROM CART C 
	JOIN PAY P ON (C.CARTNO = P.CARTNO)
)
SET CART.STATENO = 2;\

UPDATE
(
	SELECT CART.CARTNO, PAY.CARTNO
	FROM CART C, PAY P
	WHERE C.CARTNO = P.CARTNO
)
SET CARTNO = 2;