/****************************************************************
                        RECIPE
*****************************************************************/


DROP TABLE RECIPE;

CREATE TABLE RECIPE(
	
	RECIPEFILE VARCHAR(4000) UNIQUE NOT NULL,
	RECIPETITLE VARCHAR(4000) NOT NULL,
	RECIPEWRITER VARCHAR(2000) NOT NULL,
	RECIPEWRITERURL VARCHAR(4000) NOT NULL,
	VIEWS NUMBER DEFAULT '0' NOT NULL,
	RECIPEURL VARCHAR(4000) UNIQUE NOT NULL
);

SELECT * FROM RECIPE;

INSERT INTO RECIPE VALUES('AAA',DEFAULT);

UPDATE RECIPE SET RECIPE_VIEWS = RECIPE_VIEWS + 1 WHERE URL = 'AAA';
/****************************************************************
                        TIP
*****************************************************************/

DROP TABLE TIP;
CREATE TABLE TIP(
	TIPTITLE VARCHAR(4000) NOT NULL,
	TIPURL VARCHAR(4000) UNIQUE NOT NULL,
	TIPFILE VARCHAR(4000) UNIQUE NOT NULL,
	VIEWS NUMBER DEFAULT '0' NOT NULL
);

SELECT * FROM TIP;

INSERT INTO RECIPE VALUES('AAA',DEFAULT);

UPDATE RECIPE SET RECIPE_VIEWS = RECIPE_VIEWS + 1 WHERE URL = 'AAA';

SELECT * FROM TIP WHERE TIPURL = '/?r=home&c=info/camptip&uid=1187';


CREATE TABLE





/****************************************************************
                        MEMBER
*****************************************************************/
DROP SEQUENCE SEQMEM;
DROP TABLE MEMBER CASCADE CONSTRAINTS;

CREATE SEQUENCE SEQMEM;
CREATE TABLE MEMBER(
    MEMNO NUMBER PRIMARY KEY NOT NULL,
    MEMNICK VARCHAR2(100) NOT NULL UNIQUE,
    MEMID VARCHAR2(100) NOT NULL UNIQUE,
    MEMPW VARCHAR2(100) NOT NULL,
    MEMNAME VARCHAR2(100) NOT NULL,
    MEMADDR VARCHAR2(1000) NOT NULL,
    MEMPHONE VARCHAR2(100) NOT NULL,
    MEMBIRTH DATE NOT NULL,
    MEMGENDER NUMBER NOT NULL,
    MEMCHK VARCHAR2(1) DEFAULT 'N' NOT NULL ,
    MEMCODE NUMBER DEFAULT '2' NOT NULL,
    MEMFILE VARCHAR2(2000) 

);

INSERT INTO  MEMBER 
VALUES(SEQMEM.NEXTVAL, 'DD', 'KK', '1234', 'FF', '12 GG 23 GG', '123455633', DATE '2015-12-17', 2, DEFAULT, DEFAULT, NULL);

DELETE FROM MEMBER WHERE MEMNICK = 'DD';

INSERT INTO  MEMBER 
VALUES(SEQMEM.NEXTVAL, '22', 'DD', '1234', 'FF', '12 GG 23 GG', '123455633','1993/01/23', 2, DEFAULT, DEFAULT, NULL);


SELECT * FROM MEMBER;
/****************************************************************
                        INQUIRY
*****************************************************************/

DROP SEQUENCE SEQINQUIRY;
DROP TABLE INQUIRYLIST cascade constraints;

CREATE SEQUENCE SEQINQUIRY;

CREATE TABLE INQUIRYLIST(
	INQUIRYNO NUMBER PRIMARY KEY NOT NULL,
	MEMNO NUMBER NOT NULL,
	INQUIRYFILE VARCHAR2(2000) NULL,
	INQUIRYCONTENT LONG NOT NULL,
	INQUIRYDATE DATE DEFAULT SYSDATE NOT NULL,
	CATEGORYNO NUMBER NOT NULL,
	CONSTRAINT FK_MEMNO FOREIGN KEY (MEMNO) references MEMBER(MEMNO),
    CONSTRAINT FK_CATEGORYNO FOREIGN KEY (CATEGORYNO) references INQUIRYCATEGORY(CATEGORYNO)
	 
);

INSERT INTO INQUIRYLIST
VALUES(SEQINQUIRY.NEXTVAL,(SELECT MEMNO FROM MEMBER WHERE MEMNO=7),'DD','DD', DEFAULT, 3);

DELETE FROM INQUIRYLIST WHERE MEMNO=7;

SELECT * FROM INQUIRYLIST;

SELECT INQUIRYLIST.MEMNO, INQUIRYCATEGORY.CATEGORYNAME
FROM INQUIRYLIST
INNER JOIN INQUIRYCATEGORY ON INQUIRYCATEGORY.CATEGORYNO = INQUIRYLIST.CATEGORYNO;


SELECT MEMBER.MEMNICK, INQUIRYLIST.*
FROM INQUIRYLIST
INNER JOIN MEMBER ON INQUIRYLIST.MEMNO = MEMBER.MEMNO
WHERE MEMNICK = 'CC';


/****************************************************************
                       INQUIRYCATEGORY
*****************************************************************/
DROP SEQUENCE SEQINQCATEGORY;
DROP TABLE INQUIRYCATEGORY;

CREATE SEQUENCE SEQINQCATEGORY;
CREATE TABLE INQUIRYCATEGORY(
	CATEGORYNO NUMBER PRIMARY KEY NOT NULL,
	CATEGORYNAME VARCHAR2(1000) NOT NULL
);

INSERT INTO INQUIRYCATEGORY
VALUES(SEQINQCATEGORY.NEXTVAL,'물품정보');


INSERT INTO INQUIRYCATEGORY
VALUES(SEQINQCATEGORY.NEXTVAL,'거래');


INSERT INTO INQUIRYCATEGORY
VALUES(SEQINQCATEGORY.NEXTVAL,'언어');

DELETE FROM INQUIRYCATEGORY WHERE CATEGORYNO = 2;

SELECT * FROM INQUIRYCATEGORY ORDER BY CATEGORYNO ASC;
